"""Frozen 2026-09-08 schema baseline for new OpenFic databases."""

import sqlalchemy as sa
from alembic import op

revision = "20260908"
down_revision = None
branch_labels = None
depends_on = None

# This is intentionally static DDL, captured from the supported 1035 source
# and adjusted for the current schema. Do not replace it with metadata.create_all.
BASELINE_DDL = (
    """CREATE TABLE agent_attachments (
	id VARCHAR(21) NOT NULL,
	session_id VARCHAR(64) NOT NULL,
	task_id VARCHAR(64) NOT NULL,
	project_id VARCHAR(64) NOT NULL,
	storage_name VARCHAR(500) NOT NULL,
	file_name VARCHAR(255) NOT NULL,
	mime_type VARCHAR(50) NOT NULL,
	size_bytes INTEGER NOT NULL,
	width INTEGER NOT NULL,
	height INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(task_id) REFERENCES tasks (id),
	UNIQUE (storage_name)
)""",
    """CREATE TABLE "agent_audit_logs" (
	id VARCHAR NOT NULL,
	created_at DATETIME NOT NULL,
	task_id VARCHAR,
	session_id VARCHAR,
	parent_session_id VARCHAR,
	child_run_id VARCHAR,
	project_id VARCHAR NOT NULL,
	chapter_id VARCHAR,
	revision_id VARCHAR,
	operation VARCHAR(50) NOT NULL,
	call_sequence INTEGER,
	model_id VARCHAR NOT NULL,
	model_provider VARCHAR(50),
	model_name VARCHAR(100),
	request_messages VARCHAR,
	response_content VARCHAR,
	response_tool_calls VARCHAR,
	tool_call_results VARCHAR,
	tokens_input INTEGER NOT NULL,
	tokens_output INTEGER NOT NULL,
	tokens_total INTEGER NOT NULL,
	token_cache INTEGER NOT NULL,
	latency_ms INTEGER,
	first_token_ms INTEGER,
	status VARCHAR(20) NOT NULL,
	error_type VARCHAR(50),
	error_message VARCHAR,
	error_status_code INTEGER,
	tool_calls_count INTEGER NOT NULL,
	tool_calls_success_count INTEGER NOT NULL,
	tool_calls_failed_count INTEGER NOT NULL,
	extra_data VARCHAR,
	category VARCHAR(50) NOT NULL, tool_references TEXT,
	PRIMARY KEY (id),
	FOREIGN KEY(task_id) REFERENCES tasks (id),
	FOREIGN KEY(project_id) REFERENCES projects (id),
	FOREIGN KEY(chapter_id) REFERENCES chapters (id),
	FOREIGN KEY(revision_id) REFERENCES revisions (id)
)""",
    """CREATE TABLE agent_child_run_requests (
	id VARCHAR NOT NULL,
	child_run_id VARCHAR(64) NOT NULL,
	parent_session_id VARCHAR(64) NOT NULL,
	parent_task_id VARCHAR(64) NOT NULL,
	request_kind VARCHAR(50) NOT NULL,
	content TEXT NOT NULL,
	status VARCHAR(20) NOT NULL,
	assistant_content TEXT,
	error TEXT,
	seq INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	started_at DATETIME,
	completed_at DATETIME,
	updated_at DATETIME NOT NULL, parent_revision_id VARCHAR(64), child_user_message_id VARCHAR(64), child_user_message_seq INTEGER, pre_request_checkpoint_id VARCHAR(128),
	PRIMARY KEY (id),
	FOREIGN KEY(child_run_id) REFERENCES agent_child_runs (id),
	FOREIGN KEY(parent_task_id) REFERENCES tasks (id)
)""",
    """CREATE TABLE agent_child_runs (
	id VARCHAR NOT NULL,
	parent_session_id VARCHAR(64) NOT NULL,
	parent_task_id VARCHAR(64) NOT NULL,
	parent_thread_id VARCHAR(128) NOT NULL,
	child_thread_id VARCHAR(128) NOT NULL,
	agent_key VARCHAR(50) NOT NULL,
	dispatch_id VARCHAR(64) NOT NULL,
	tool_call_id VARCHAR(64) NOT NULL,
	status VARCHAR(20) NOT NULL,
	is_active BOOLEAN NOT NULL,
	request_json JSON NOT NULL,
	result_json JSON,
	pending_approval_id VARCHAR(128),
	pending_approval_json JSON,
	error TEXT,
	recycled_at DATETIME,
	last_assistant_content TEXT,
	last_user_message_at DATETIME,
	last_completed_at DATETIME,
	metadata_json JSON NOT NULL,
	started_at DATETIME,
	completed_at DATETIME,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL, parent_revision_id VARCHAR(64),
	PRIMARY KEY (id),
	FOREIGN KEY(parent_task_id) REFERENCES tasks (id)
)""",
    """CREATE TABLE agent_context_compactions (
	id VARCHAR NOT NULL,
	session_id VARCHAR(64) NOT NULL,
	task_id VARCHAR(64) NOT NULL,
	project_id VARCHAR(64) NOT NULL,
	start_seq INTEGER NOT NULL,
	end_seq INTEGER NOT NULL,
	summary TEXT NOT NULL,
	"trigger" VARCHAR(20) NOT NULL,
	source_input_tokens INTEGER NOT NULL,
	summary_tokens INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT ck_agent_context_compactions_end_seq_nonnegative CHECK (end_seq >= 0),
	CONSTRAINT ck_agent_context_compactions_source_input_tokens_nonnegative CHECK (source_input_tokens >= 0),
	CONSTRAINT ck_agent_context_compactions_valid_range CHECK (start_seq <= end_seq),
	CONSTRAINT ck_agent_context_compactions_start_seq_nonnegative CHECK (start_seq >= 0),
	CONSTRAINT ck_agent_context_compactions_summary_tokens_nonnegative CHECK (summary_tokens >= 0),
	FOREIGN KEY(task_id) REFERENCES tasks (id)
)""",
    """CREATE TABLE "agent_definitions" (
	id VARCHAR NOT NULL,
	"key" VARCHAR(50) NOT NULL,
	display_name VARCHAR(200) NOT NULL,
	description TEXT NOT NULL,
	kind VARCHAR(20) NOT NULL,
	prompt_agent_name VARCHAR(50) NOT NULL,
	model_id VARCHAR(100),
	enabled_tool_categories JSON NOT NULL,
	metadata_json JSON NOT NULL,
	enabled BOOLEAN NOT NULL,
	order_index INTEGER NOT NULL,
	source VARCHAR(20) NOT NULL,
	delegatable_agents JSON NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	enabled_skills JSON DEFAULT '[]' NOT NULL, color VARCHAR(20), icon VARCHAR(30),
	PRIMARY KEY (id)
)""",
    """CREATE TABLE agent_memories (
	id VARCHAR NOT NULL,
	content VARCHAR NOT NULL,
	order_index INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id)
)""",
    """CREATE TABLE agent_rules (
	id VARCHAR NOT NULL,
	title VARCHAR NOT NULL,
	content VARCHAR NOT NULL,
	order_index INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL, scope VARCHAR(16) DEFAULT 'global' NOT NULL, project_id VARCHAR(64), token_count INTEGER DEFAULT '0' NOT NULL,
	PRIMARY KEY (id)
)""",
    """CREATE TABLE agent_run_messages (
	id VARCHAR NOT NULL,
	session_id VARCHAR(64) NOT NULL,
	task_id VARCHAR(64) NOT NULL,
	project_id VARCHAR(64) NOT NULL,
	role VARCHAR(20) NOT NULL,
	agent_id VARCHAR(50),
	content TEXT NOT NULL,
	reasoning TEXT,
	reasoning_duration_ms INTEGER,
	tool_calls TEXT,
	tool_call_id VARCHAR(64),
	tool_name VARCHAR(64),
	status VARCHAR(20) NOT NULL,
	message_type VARCHAR(50) NOT NULL,
	display_channel VARCHAR(20) NOT NULL,
	llm_visibility VARCHAR(20) NOT NULL,
	seq INTEGER NOT NULL,
	metadata TEXT NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(task_id) REFERENCES tasks (id)
)""",
    """CREATE TABLE background_job_events (
	id VARCHAR NOT NULL,
	job_id VARCHAR NOT NULL,
	item_id VARCHAR,
	sequence INTEGER NOT NULL,
	event_type VARCHAR(100) NOT NULL,
	payload_json VARCHAR NOT NULL,
	created_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(item_id) REFERENCES background_job_items (id),
	FOREIGN KEY(job_id) REFERENCES background_jobs (id)
)""",
    """CREATE TABLE background_job_items (
	id VARCHAR NOT NULL,
	job_id VARCHAR NOT NULL,
	item_key VARCHAR(200) NOT NULL,
	type VARCHAR(80) NOT NULL,
	status VARCHAR(30) NOT NULL,
	payload_json VARCHAR NOT NULL,
	result_json VARCHAR,
	error_json VARCHAR,
	progress_json VARCHAR NOT NULL,
	order_index INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	started_at DATETIME,
	finished_at DATETIME,
	PRIMARY KEY (id),
	FOREIGN KEY(job_id) REFERENCES background_jobs (id)
)""",
    """CREATE TABLE background_jobs (
	id VARCHAR NOT NULL,
	type VARCHAR(80) NOT NULL,
	status VARCHAR(30) NOT NULL,
	queue VARCHAR(80) NOT NULL,
	subject_type VARCHAR(80),
	subject_id VARCHAR,
	payload_json VARCHAR NOT NULL,
	context_json VARCHAR NOT NULL,
	progress_json VARCHAR NOT NULL,
	result_json VARCHAR,
	error_json VARCHAR,
	attempt_count INTEGER NOT NULL,
	max_attempts INTEGER NOT NULL,
	event_sequence INTEGER NOT NULL,
	timeout_seconds INTEGER,
	next_run_at DATETIME,
	locked_by VARCHAR(100),
	locked_at DATETIME,
	heartbeat_at DATETIME,
	lease_expires_at DATETIME,
	cancel_requested_at DATETIME,
	cancel_reason VARCHAR,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	started_at DATETIME,
	finished_at DATETIME,
	PRIMARY KEY (id)
)""",
    """CREATE TABLE "chapter_summaries" (
	id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	summary_type VARCHAR(20) NOT NULL,
	status VARCHAR(30) NOT NULL,
	chapter_id VARCHAR,
	volume_id VARCHAR,
	chapter_order INTEGER,
	start_order INTEGER,
	end_order INTEGER,
	start_time VARCHAR NOT NULL,
	end_time VARCHAR NOT NULL,
	characters_json VARCHAR NOT NULL,
	locations_json VARCHAR NOT NULL,
	summary VARCHAR NOT NULL,
	token_count INTEGER NOT NULL,
	error_message VARCHAR,
	source_content_normalized VARCHAR NOT NULL,
	source_chapter_ids_json VARCHAR NOT NULL,
	source_chapter_summary_signatures_json VARCHAR NOT NULL,
	model_id VARCHAR(200),
	job_id VARCHAR,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_chapter_summaries_chapter_id_chapters FOREIGN KEY(chapter_id) REFERENCES chapters (id),
	CONSTRAINT fk_chapter_summaries_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id),
	CONSTRAINT fk_chapter_summaries_volume_id_project_folders FOREIGN KEY(volume_id) REFERENCES project_folders (id) ON DELETE SET NULL
)""",
    """CREATE TABLE "chapters" (
	id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	volume_id VARCHAR,
	title VARCHAR(200) NOT NULL,
	content VARCHAR NOT NULL,
	word_count INTEGER NOT NULL,
	"order" INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_chapters_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id),
	CONSTRAINT uq_chapters_volume_order UNIQUE (volume_id, "order"),
	CONSTRAINT fk_chapters_volume_id_project_folders FOREIGN KEY(volume_id) REFERENCES project_folders (id) ON DELETE SET NULL
)""",
    """CREATE TABLE "characters" (
	id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	name VARCHAR(200) NOT NULL,
	description VARCHAR NOT NULL,
	image_path VARCHAR,
	is_favorited BOOLEAN DEFAULT '0' NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	"order" INTEGER NOT NULL,
	folder_id VARCHAR(21),
	agent_visibility VARCHAR DEFAULT 'all' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_characters_folder_id_project_folders FOREIGN KEY(folder_id) REFERENCES project_folders (id) ON DELETE SET NULL,
	FOREIGN KEY(project_id) REFERENCES projects (id)
)""",
    """CREATE TABLE commits (
	id VARCHAR NOT NULL,
	revision_id VARCHAR NOT NULL,
	chapter_id VARCHAR NOT NULL,
	operation VARCHAR(20) NOT NULL,
	snapshot_title VARCHAR(200),
	snapshot_content VARCHAR,
	snapshot_word_count INTEGER,
	snapshot_order INTEGER,
	new_title VARCHAR(200),
	new_content VARCHAR,
	new_word_count INTEGER,
	new_order INTEGER,
	created_at DATETIME NOT NULL, snapshot_content_blob_id VARCHAR(64), new_content_blob_id VARCHAR(64),
	PRIMARY KEY (id),
	FOREIGN KEY(chapter_id) REFERENCES chapters (id),
	FOREIGN KEY(revision_id) REFERENCES revisions (id)
)""",
    """CREATE TABLE "model_providers" (
	id VARCHAR NOT NULL,
	name VARCHAR(200) NOT NULL,
	url VARCHAR(500) NOT NULL,
	api_key_encrypted VARCHAR(1000) NOT NULL,
	provider_type VARCHAR(50) NOT NULL,
	is_builtin BOOLEAN NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL, custom_headers_encrypted TEXT DEFAULT '' NOT NULL,
	PRIMARY KEY (id)
)""",
    """CREATE TABLE "models" (
	id VARCHAR NOT NULL,
	name VARCHAR(200) NOT NULL,
	remark VARCHAR(500) NOT NULL,
	provider_id VARCHAR NOT NULL,
	model_id VARCHAR(200) NOT NULL,
	task_type VARCHAR(20) NOT NULL,
	temperature FLOAT,
	top_p FLOAT,
	top_k INTEGER,
	min_p FLOAT,
	top_a FLOAT,
	frequency_penalty FLOAT,
	presence_penalty FLOAT,
	repetition_penalty FLOAT,
	max_tokens INTEGER,
	context_length INTEGER NOT NULL,
	dimensions INTEGER,
	is_builtin BOOLEAN NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	input_price FLOAT DEFAULT '0' NOT NULL,
	output_price FLOAT DEFAULT '0' NOT NULL,
	cache_read_price FLOAT DEFAULT '0' NOT NULL,
	cache_write_price FLOAT DEFAULT '0' NOT NULL,
	is_enabled BOOLEAN NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(provider_id) REFERENCES model_providers (id)
)""",
    """CREATE TABLE "notes" (
	id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	category_id VARCHAR,
	title VARCHAR(200) NOT NULL,
	content VARCHAR NOT NULL,
	is_locked BOOLEAN NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	"order" INTEGER NOT NULL,
	document_type VARCHAR(20) NOT NULL,
	agent_visibility VARCHAR DEFAULT 'all' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_notes_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id),
	CONSTRAINT fk_notes_category_id_project_folders FOREIGN KEY(category_id) REFERENCES project_folders (id) ON DELETE SET NULL,
	CONSTRAINT ck_notes_document_type CHECK (document_type IN ('note', 'outline'))
)""",
    """CREATE TABLE "pending_project_changes" (
	id VARCHAR(21) NOT NULL,
	project_id VARCHAR(21) NOT NULL,
	target_type VARCHAR(100) NOT NULL,
	target_id VARCHAR(200),
	operation VARCHAR(20) NOT NULL,
	base_hash VARCHAR(128),
	"before" JSON,
	"after" JSON,
	source_task_id VARCHAR(128),
	source_message_id VARCHAR(128),
	model_id VARCHAR(200),
	status VARCHAR(20) DEFAULT 'pending' NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	applied_at DATETIME,
	PRIMARY KEY (id),
	CONSTRAINT fk_pending_project_changes_project_id FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE,
	CONSTRAINT ck_pending_project_changes_operation CHECK (operation IN ('create', 'update', 'delete')),
	CONSTRAINT ck_pending_project_changes_status CHECK (status IN ('pending', 'applying', 'rejected', 'applied'))
)""",
    """CREATE TABLE "plan_todos" (
	id VARCHAR NOT NULL,
	plan_id VARCHAR(64) NOT NULL,
	content TEXT NOT NULL,
	status VARCHAR(20) NOT NULL,
	sort_index INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	priority VARCHAR(20) DEFAULT 'medium' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_plan_todos_plan_id_sort_index UNIQUE (plan_id, sort_index),
	FOREIGN KEY(plan_id) REFERENCES plans (id)
)""",
    """CREATE TABLE "plans" (
	id VARCHAR NOT NULL,
	session_id VARCHAR(64) NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id)
)""",
    """CREATE TABLE "project_folders" (
	id VARCHAR(21) NOT NULL,
	project_id VARCHAR(21) NOT NULL,
	scope VARCHAR(20) NOT NULL,
	title VARCHAR(200) NOT NULL,
	"order" INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	description TEXT,
	item_count INTEGER DEFAULT '0' NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE
)""",
    """CREATE TABLE "project_import_bindings" (
	id VARCHAR(21) NOT NULL,
	project_id VARCHAR(21) NOT NULL,
	binding_key VARCHAR(64) NOT NULL,
	rule_id VARCHAR(200) NOT NULL,
	source_path VARCHAR(1000) NOT NULL,
	source_anchor VARCHAR(2000) NOT NULL,
	target_kind VARCHAR(30) NOT NULL,
	target_id VARCHAR(64) NOT NULL,
	last_applied_hash VARCHAR(71) NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_project_import_bindings_project_target UNIQUE (project_id, target_kind, target_id),
	CONSTRAINT fk_project_import_bindings_project_id FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE,
	CONSTRAINT uq_project_import_bindings_project_key UNIQUE (project_id, binding_key),
	CONSTRAINT ck_project_import_bindings_target_kind CHECK (target_kind IN ('world_entry', 'character', 'chapter', 'note', 'note_category', 'project_folder', 'discussion', 'discussion_message'))
)""",
    """CREATE TABLE project_import_profiles (
	project_id VARCHAR(21) NOT NULL,
	mapping_yaml TEXT NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (project_id),
	CONSTRAINT fk_project_import_profiles_project_id FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE
)""",
    """CREATE TABLE projects (
	id VARCHAR NOT NULL,
	title VARCHAR(200) NOT NULL,
	description VARCHAR,
	word_count INTEGER NOT NULL,
	chapter_count INTEGER NOT NULL,
	cover_path VARCHAR,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id)
)""",
    """CREATE TABLE "prompt_chain_versions" (
	id VARCHAR NOT NULL,
	version_hash VARCHAR(8) NOT NULL,
	version_number INTEGER NOT NULL,
	parent_version_id VARCHAR,
	is_active BOOLEAN NOT NULL,
	note VARCHAR(500),
	created_at DATETIME NOT NULL,
	prompt_id VARCHAR(300) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (version_hash),
	FOREIGN KEY(parent_version_id) REFERENCES prompt_chain_versions (id)
)""",
    """CREATE TABLE prompt_entries (
	id VARCHAR NOT NULL,
	uid VARCHAR NOT NULL,
	version_id VARCHAR NOT NULL,
	name VARCHAR(200) NOT NULL,
	role VARCHAR(20) NOT NULL,
	content VARCHAR NOT NULL,
	order_index INTEGER NOT NULL,
	is_enabled BOOLEAN NOT NULL,
	token_count INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(version_id) REFERENCES prompt_chain_versions (id)
)""",
    """CREATE TABLE retrieval_chapter_index_states (
	id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	chapter_id VARCHAR NOT NULL,
	index_key VARCHAR(200) NOT NULL,
	status VARCHAR(30) NOT NULL,
	source_hash VARCHAR(128),
	embedding_model_ref_id VARCHAR(200),
	chunk_count INTEGER,
	job_id VARCHAR,
	item_id VARCHAR,
	indexed_at DATETIME,
	error_message VARCHAR,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(chapter_id) REFERENCES chapters (id),
	FOREIGN KEY(embedding_model_ref_id) REFERENCES models (id),
	FOREIGN KEY(item_id) REFERENCES background_job_items (id),
	FOREIGN KEY(job_id) REFERENCES background_jobs (id),
	FOREIGN KEY(project_id) REFERENCES projects (id),
	CONSTRAINT uq_retrieval_chapter_index_state UNIQUE (project_id, chapter_id, index_key)
)""",
    """CREATE TABLE retrieval_indexes (
	id VARCHAR NOT NULL,
	index_key VARCHAR(200) NOT NULL,
	table_name VARCHAR(200) NOT NULL,
	status VARCHAR(20) NOT NULL,
	embedding_model_ref_id VARCHAR(200) NOT NULL,
	embedding_model_id_snapshot VARCHAR(200) NOT NULL,
	embedding_dimensions_snapshot INTEGER NOT NULL,
	distance_metric VARCHAR(20) NOT NULL,
	chunker_type VARCHAR(50) NOT NULL,
	chunk_size INTEGER NOT NULL,
	chunk_overlap INTEGER NOT NULL,
	filterable_fields_json VARCHAR NOT NULL,
	vector_index_type VARCHAR(50) NOT NULL,
	vector_index_params_json VARCHAR NOT NULL,
	fts_index_params_json VARCHAR NOT NULL,
	schema_version INTEGER NOT NULL,
	last_error VARCHAR,
	last_build_at DATETIME,
	last_ready_at DATETIME,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(embedding_model_ref_id) REFERENCES models (id)
)""",
    """CREATE TABLE revision_chapter_snapshots (
	id VARCHAR NOT NULL,
	revision_id VARCHAR NOT NULL,
	chapter_id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	volume_id VARCHAR,
	"exists" BOOLEAN NOT NULL,
	title VARCHAR(200),
	content VARCHAR,
	word_count INTEGER,
	chapter_order INTEGER,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL, content_blob_id VARCHAR(64),
	PRIMARY KEY (id),
	FOREIGN KEY(project_id) REFERENCES projects (id),
	FOREIGN KEY(revision_id) REFERENCES revisions (id),
	CONSTRAINT uq_revision_chapter_snapshot UNIQUE (revision_id, chapter_id)
)""",
    """CREATE TABLE "revision_character_snapshots" (
	id VARCHAR NOT NULL,
	revision_id VARCHAR NOT NULL,
	character_id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	"exists" BOOLEAN NOT NULL,
	name VARCHAR(200),
	description VARCHAR,
	is_favorited BOOLEAN,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	description_blob_id VARCHAR(64),
	character_order INTEGER,
	agent_visibility VARCHAR,
	PRIMARY KEY (id),
	CONSTRAINT uq_revision_character_snapshot UNIQUE (revision_id, character_id),
	FOREIGN KEY(project_id) REFERENCES projects (id),
	FOREIGN KEY(revision_id) REFERENCES revisions (id)
)""",
    """CREATE TABLE revision_content_blobs (
	id VARCHAR(64) NOT NULL,
	data BLOB NOT NULL,
	raw_size INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	PRIMARY KEY (id)
)""",
    """CREATE TABLE revision_note_category_snapshots (
	id VARCHAR NOT NULL,
	revision_id VARCHAR NOT NULL,
	category_id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	"exists" BOOLEAN NOT NULL,
	parent_id VARCHAR,
	title VARCHAR(200),
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL, category_order INTEGER, scope VARCHAR DEFAULT 'note' NOT NULL, description TEXT,
	PRIMARY KEY (id),
	FOREIGN KEY(project_id) REFERENCES projects (id),
	FOREIGN KEY(revision_id) REFERENCES revisions (id),
	CONSTRAINT uq_revision_note_category_snapshot UNIQUE (revision_id, category_id)
)""",
    """CREATE TABLE "revision_note_snapshots" (
	id VARCHAR NOT NULL,
	revision_id VARCHAR NOT NULL,
	note_id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	"exists" BOOLEAN NOT NULL,
	category_id VARCHAR,
	title VARCHAR(200),
	content VARCHAR,
	is_locked BOOLEAN,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	content_blob_id VARCHAR(64),
	note_order INTEGER,
	document_type VARCHAR DEFAULT 'note' NOT NULL,
	agent_visibility VARCHAR,
	PRIMARY KEY (id),
	CONSTRAINT uq_revision_note_snapshot UNIQUE (revision_id, note_id),
	FOREIGN KEY(project_id) REFERENCES projects (id),
	FOREIGN KEY(revision_id) REFERENCES revisions (id)
)""",
    """CREATE TABLE "revision_world_entry_snapshots" (
	id VARCHAR NOT NULL,
	revision_id VARCHAR NOT NULL,
	entry_id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	"exists" BOOLEAN NOT NULL,
	world_info_id VARCHAR,
	uid INTEGER,
	name VARCHAR(200),
	entry_order INTEGER,
	content VARCHAR,
	token_count INTEGER,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	content_blob_id VARCHAR(64),
	section VARCHAR(500),
	agent_visibility VARCHAR,
	PRIMARY KEY (id),
	CONSTRAINT uq_revision_world_entry_snapshot UNIQUE (revision_id, entry_id),
	FOREIGN KEY(project_id) REFERENCES projects (id),
	FOREIGN KEY(revision_id) REFERENCES revisions (id)
)""",
    """CREATE TABLE revisions (
	id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	message VARCHAR NOT NULL,
	agent_session_id VARCHAR,
	status VARCHAR NOT NULL,
	revision_type VARCHAR NOT NULL,
	parent_revision_id VARCHAR,
	task_id VARCHAR,
	user_message_id VARCHAR,
	user_message_seq INTEGER,
	pre_run_checkpoint_id VARCHAR,
	graph_thread_id VARCHAR,
	is_checkpoint BOOLEAN NOT NULL,
	project_snapshot_title VARCHAR(200) NOT NULL,
	project_snapshot_description VARCHAR,
	project_snapshot_word_count INTEGER NOT NULL,
	project_snapshot_chapter_count INTEGER NOT NULL,
	started_at DATETIME,
	finished_at DATETIME,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(parent_revision_id) REFERENCES revisions (id),
	FOREIGN KEY(project_id) REFERENCES projects (id),
	CONSTRAINT fk_revisions_task_id_tasks FOREIGN KEY(task_id) REFERENCES tasks (id)
)""",
    """CREATE TABLE settings (
	id VARCHAR NOT NULL,
	"key" VARCHAR(100) NOT NULL,
	value VARCHAR NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id)
)""",
    """CREATE TABLE skill_reference_docs (
	id VARCHAR NOT NULL,
	skill_db_id VARCHAR NOT NULL,
	title VARCHAR(200) NOT NULL,
	content VARCHAR NOT NULL,
	tokens INTEGER DEFAULT '0' NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(skill_db_id) REFERENCES skills (id)
)""",
    """CREATE TABLE "skills" (
	id VARCHAR NOT NULL,
	name VARCHAR(200) NOT NULL,
	summary VARCHAR NOT NULL,
	content VARCHAR NOT NULL,
	is_enabled BOOLEAN NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id)
)""",
    """CREATE TABLE task_messages (
	id VARCHAR NOT NULL,
	task_id VARCHAR NOT NULL,
	role VARCHAR(20) NOT NULL,
	agent_id VARCHAR(50),
	content VARCHAR NOT NULL,
	tool_calls VARCHAR NOT NULL,
	tool_call_id VARCHAR,
	metadata TEXT NOT NULL,
	message_type VARCHAR,
	message_status VARCHAR,
	display_channel VARCHAR,
	payload TEXT,
	correlation_id VARCHAR,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(task_id) REFERENCES tasks (id)
)""",
    """CREATE TABLE "tasks" (
	id VARCHAR NOT NULL,
	project_id VARCHAR NOT NULL,
	title VARCHAR(200) NOT NULL,
	mode VARCHAR(20) NOT NULL,
	token_input INTEGER NOT NULL,
	token_output INTEGER NOT NULL,
	token_cache INTEGER NOT NULL,
	context_input_tokens INTEGER NOT NULL,
	current_revision_id VARCHAR,
	current_message_id VARCHAR,
	agent_session_id VARCHAR,
	is_running BOOLEAN NOT NULL,
	is_favorited BOOLEAN NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	cost FLOAT DEFAULT '0' NOT NULL,
	context_mode VARCHAR(20) NOT NULL,
	is_imported_archive BOOLEAN NOT NULL,
	folder_id VARCHAR(21),
	PRIMARY KEY (id),
	CONSTRAINT ck_tasks_context_mode CHECK (context_mode IN ('global', 'local')),
	CONSTRAINT fk_tasks_folder_id_project_folders FOREIGN KEY(folder_id) REFERENCES project_folders (id) ON DELETE SET NULL,
	FOREIGN KEY(current_revision_id) REFERENCES revisions (id),
	FOREIGN KEY(project_id) REFERENCES projects (id)
)""",
    """CREATE TABLE world_info (
	id VARCHAR NOT NULL,
	project_id VARCHAR,
	name VARCHAR(200) NOT NULL,
	description VARCHAR NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(project_id) REFERENCES projects (id)
)""",
    """CREATE TABLE "world_info_entries" (
	id VARCHAR NOT NULL,
	world_info_id VARCHAR NOT NULL,
	uid INTEGER NOT NULL,
	name VARCHAR(200) NOT NULL,
	"order" INTEGER NOT NULL,
	content VARCHAR NOT NULL,
	token_count INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	section VARCHAR(500) NOT NULL,
	folder_id VARCHAR(21),
	agent_visibility VARCHAR DEFAULT 'all' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_world_info_entries_folder_id_project_folders FOREIGN KEY(folder_id) REFERENCES project_folders (id) ON DELETE SET NULL,
	FOREIGN KEY(world_info_id) REFERENCES world_info (id)
)""",
    """CREATE TABLE writing_activity_events (
	id VARCHAR NOT NULL,
	created_at DATETIME NOT NULL,
	project_id VARCHAR NOT NULL,
	chapter_id VARCHAR,
	chapter_title VARCHAR(200),
	source VARCHAR(30) NOT NULL,
	operation VARCHAR(30) NOT NULL,
	old_word_count INTEGER NOT NULL,
	new_word_count INTEGER NOT NULL,
	word_delta INTEGER NOT NULL,
	revision_id VARCHAR,
	task_id VARCHAR,
	agent_session_id VARCHAR,
	PRIMARY KEY (id)
)""",
    """CREATE INDEX ix_agent_attachments_created_at ON agent_attachments (created_at)""",
    """CREATE INDEX ix_agent_attachments_project_id ON agent_attachments (project_id)""",
    """CREATE INDEX ix_agent_attachments_session_id ON agent_attachments (session_id)""",
    """CREATE INDEX ix_agent_attachments_task_id ON agent_attachments (task_id)""",
    """CREATE INDEX ix_agent_audit_logs_category ON agent_audit_logs (category)""",
    """CREATE INDEX ix_agent_audit_logs_chapter_id ON agent_audit_logs (chapter_id)""",
    """CREATE INDEX ix_agent_audit_logs_child_run_id ON agent_audit_logs (child_run_id)""",
    """CREATE INDEX ix_agent_audit_logs_created_at ON agent_audit_logs (created_at)""",
    """CREATE INDEX ix_agent_audit_logs_model_id ON agent_audit_logs (model_id)""",
    """CREATE INDEX ix_agent_audit_logs_model_provider ON agent_audit_logs (model_provider)""",
    """CREATE INDEX ix_agent_audit_logs_operation ON agent_audit_logs (operation)""",
    """CREATE INDEX ix_agent_audit_logs_parent_session_id ON agent_audit_logs (parent_session_id)""",
    """CREATE INDEX ix_agent_audit_logs_project_id ON agent_audit_logs (project_id)""",
    """CREATE INDEX ix_agent_audit_logs_revision_id ON agent_audit_logs (revision_id)""",
    """CREATE INDEX ix_agent_audit_logs_session_id ON agent_audit_logs (session_id)""",
    """CREATE INDEX ix_agent_audit_logs_status ON agent_audit_logs (status)""",
    """CREATE INDEX ix_agent_audit_logs_task_id ON agent_audit_logs (task_id)""",
    """CREATE INDEX ix_agent_child_run_requests_child_run_id ON agent_child_run_requests (child_run_id)""",
    """CREATE INDEX ix_agent_child_run_requests_child_user_message_id ON agent_child_run_requests (child_user_message_id)""",
    """CREATE INDEX ix_agent_child_run_requests_child_user_message_seq ON agent_child_run_requests (child_user_message_seq)""",
    """CREATE INDEX ix_agent_child_run_requests_completed_at ON agent_child_run_requests (completed_at)""",
    """CREATE INDEX ix_agent_child_run_requests_created_at ON agent_child_run_requests (created_at)""",
    """CREATE INDEX ix_agent_child_run_requests_parent_revision_id ON agent_child_run_requests (parent_revision_id)""",
    """CREATE INDEX ix_agent_child_run_requests_parent_session_id ON agent_child_run_requests (parent_session_id)""",
    """CREATE INDEX ix_agent_child_run_requests_parent_task_id ON agent_child_run_requests (parent_task_id)""",
    """CREATE INDEX ix_agent_child_run_requests_pre_request_checkpoint_id ON agent_child_run_requests (pre_request_checkpoint_id)""",
    """CREATE INDEX ix_agent_child_run_requests_request_kind ON agent_child_run_requests (request_kind)""",
    """CREATE INDEX ix_agent_child_run_requests_seq ON agent_child_run_requests (seq)""",
    """CREATE INDEX ix_agent_child_run_requests_started_at ON agent_child_run_requests (started_at)""",
    """CREATE INDEX ix_agent_child_run_requests_status ON agent_child_run_requests (status)""",
    """CREATE INDEX ix_agent_child_runs_agent_key ON agent_child_runs (agent_key)""",
    """CREATE INDEX ix_agent_child_runs_child_thread_id ON agent_child_runs (child_thread_id)""",
    """CREATE INDEX ix_agent_child_runs_completed_at ON agent_child_runs (completed_at)""",
    """CREATE INDEX ix_agent_child_runs_created_at ON agent_child_runs (created_at)""",
    """CREATE INDEX ix_agent_child_runs_dispatch_id ON agent_child_runs (dispatch_id)""",
    """CREATE INDEX ix_agent_child_runs_is_active ON agent_child_runs (is_active)""",
    """CREATE INDEX ix_agent_child_runs_last_completed_at ON agent_child_runs (last_completed_at)""",
    """CREATE INDEX ix_agent_child_runs_last_user_message_at ON agent_child_runs (last_user_message_at)""",
    """CREATE INDEX ix_agent_child_runs_parent_revision_id ON agent_child_runs (parent_revision_id)""",
    """CREATE INDEX ix_agent_child_runs_parent_session_id ON agent_child_runs (parent_session_id)""",
    """CREATE INDEX ix_agent_child_runs_parent_task_id ON agent_child_runs (parent_task_id)""",
    """CREATE INDEX ix_agent_child_runs_parent_thread_id ON agent_child_runs (parent_thread_id)""",
    """CREATE INDEX ix_agent_child_runs_pending_approval_id ON agent_child_runs (pending_approval_id)""",
    """CREATE INDEX ix_agent_child_runs_recycled_at ON agent_child_runs (recycled_at)""",
    """CREATE INDEX ix_agent_child_runs_started_at ON agent_child_runs (started_at)""",
    """CREATE INDEX ix_agent_child_runs_status ON agent_child_runs (status)""",
    """CREATE INDEX ix_agent_child_runs_tool_call_id ON agent_child_runs (tool_call_id)""",
    """CREATE INDEX ix_agent_context_compactions_created_at ON agent_context_compactions (created_at)""",
    """CREATE INDEX ix_agent_context_compactions_end_seq ON agent_context_compactions (end_seq)""",
    """CREATE INDEX ix_agent_context_compactions_project_id ON agent_context_compactions (project_id)""",
    """CREATE INDEX ix_agent_context_compactions_session_id ON agent_context_compactions (session_id)""",
    """CREATE INDEX ix_agent_context_compactions_session_start_end ON agent_context_compactions (session_id, start_seq, end_seq)""",
    """CREATE INDEX ix_agent_context_compactions_start_seq ON agent_context_compactions (start_seq)""",
    """CREATE INDEX ix_agent_context_compactions_task_id ON agent_context_compactions (task_id)""",
    """CREATE INDEX ix_agent_context_compactions_trigger ON agent_context_compactions ("trigger")""",
    """CREATE INDEX ix_agent_definitions_enabled ON agent_definitions (enabled)""",
    """CREATE UNIQUE INDEX ix_agent_definitions_key ON agent_definitions ("key")""",
    """CREATE INDEX ix_agent_definitions_kind ON agent_definitions (kind)""",
    """CREATE INDEX ix_agent_definitions_order_index ON agent_definitions (order_index)""",
    """CREATE INDEX ix_agent_definitions_source ON agent_definitions (source)""",
    """CREATE INDEX ix_agent_rules_project_id ON agent_rules (project_id)""",
    """CREATE INDEX ix_agent_rules_scope ON agent_rules (scope)""",
    """CREATE INDEX ix_agent_run_messages_agent_id ON agent_run_messages (agent_id)""",
    """CREATE INDEX ix_agent_run_messages_created_at ON agent_run_messages (created_at)""",
    """CREATE INDEX ix_agent_run_messages_display_channel ON agent_run_messages (display_channel)""",
    """CREATE INDEX ix_agent_run_messages_llm_visibility ON agent_run_messages (llm_visibility)""",
    """CREATE INDEX ix_agent_run_messages_message_type ON agent_run_messages (message_type)""",
    """CREATE INDEX ix_agent_run_messages_project_id ON agent_run_messages (project_id)""",
    """CREATE INDEX ix_agent_run_messages_role ON agent_run_messages (role)""",
    """CREATE INDEX ix_agent_run_messages_seq ON agent_run_messages (seq)""",
    """CREATE INDEX ix_agent_run_messages_session_id ON agent_run_messages (session_id)""",
    """CREATE INDEX ix_agent_run_messages_status ON agent_run_messages (status)""",
    """CREATE INDEX ix_agent_run_messages_task_id ON agent_run_messages (task_id)""",
    """CREATE INDEX ix_agent_run_messages_tool_call_id ON agent_run_messages (tool_call_id)""",
    """CREATE INDEX ix_background_job_events_created_at ON background_job_events (created_at)""",
    """CREATE INDEX ix_background_job_events_event_type ON background_job_events (event_type)""",
    """CREATE INDEX ix_background_job_events_item_id ON background_job_events (item_id)""",
    """CREATE INDEX ix_background_job_events_job_id ON background_job_events (job_id)""",
    """CREATE INDEX ix_background_job_events_sequence ON background_job_events (sequence)""",
    """CREATE INDEX ix_background_job_items_item_key ON background_job_items (item_key)""",
    """CREATE INDEX ix_background_job_items_job_id ON background_job_items (job_id)""",
    """CREATE INDEX ix_background_job_items_order_index ON background_job_items (order_index)""",
    """CREATE INDEX ix_background_job_items_status ON background_job_items (status)""",
    """CREATE INDEX ix_background_job_items_type ON background_job_items (type)""",
    """CREATE INDEX ix_background_job_items_updated_at ON background_job_items (updated_at)""",
    """CREATE INDEX ix_background_jobs_cancel_requested_at ON background_jobs (cancel_requested_at)""",
    """CREATE INDEX ix_background_jobs_heartbeat_at ON background_jobs (heartbeat_at)""",
    """CREATE INDEX ix_background_jobs_lease_expires_at ON background_jobs (lease_expires_at)""",
    """CREATE INDEX ix_background_jobs_locked_at ON background_jobs (locked_at)""",
    """CREATE INDEX ix_background_jobs_locked_by ON background_jobs (locked_by)""",
    """CREATE INDEX ix_background_jobs_next_run_at ON background_jobs (next_run_at)""",
    """CREATE INDEX ix_background_jobs_queue ON background_jobs (queue)""",
    """CREATE INDEX ix_background_jobs_status ON background_jobs (status)""",
    """CREATE INDEX ix_background_jobs_subject_id ON background_jobs (subject_id)""",
    """CREATE INDEX ix_background_jobs_subject_type ON background_jobs (subject_type)""",
    """CREATE INDEX ix_background_jobs_type ON background_jobs (type)""",
    """CREATE INDEX ix_background_jobs_updated_at ON background_jobs (updated_at)""",
    """CREATE INDEX ix_chapter_summaries_chapter_id ON chapter_summaries (chapter_id)""",
    """CREATE INDEX ix_chapter_summaries_chapter_order ON chapter_summaries (chapter_order)""",
    """CREATE INDEX ix_chapter_summaries_end_order ON chapter_summaries (end_order)""",
    """CREATE INDEX ix_chapter_summaries_job_id ON chapter_summaries (job_id)""",
    """CREATE INDEX ix_chapter_summaries_project_id ON chapter_summaries (project_id)""",
    """CREATE INDEX ix_chapter_summaries_start_order ON chapter_summaries (start_order)""",
    """CREATE INDEX ix_chapter_summaries_status ON chapter_summaries (status)""",
    """CREATE INDEX ix_chapter_summaries_summary_type ON chapter_summaries (summary_type)""",
    """CREATE INDEX ix_chapter_summaries_volume_id ON chapter_summaries (volume_id)""",
    """CREATE INDEX ix_chapters_order ON chapters ("order")""",
    """CREATE INDEX ix_chapters_project_id ON chapters (project_id)""",
    """CREATE INDEX ix_chapters_volume_id ON chapters (volume_id)""",
    """CREATE INDEX ix_characters_agent_visibility ON characters (agent_visibility)""",
    """CREATE INDEX ix_characters_folder_id ON characters (folder_id)""",
    """CREATE INDEX ix_characters_is_favorited ON characters (is_favorited)""",
    """CREATE INDEX ix_characters_order ON characters ("order")""",
    """CREATE INDEX ix_characters_project_id ON characters (project_id)""",
    """CREATE INDEX ix_characters_updated_at ON characters (updated_at)""",
    """CREATE INDEX ix_commits_chapter_id ON commits (chapter_id)""",
    """CREATE INDEX ix_commits_revision_id ON commits (revision_id)""",
    """CREATE INDEX ix_models_is_enabled ON models (is_enabled)""",
    """CREATE INDEX ix_models_provider_id ON models (provider_id)""",
    """CREATE INDEX ix_models_task_type ON models (task_type)""",
    """CREATE INDEX ix_notes_agent_visibility ON notes (agent_visibility)""",
    """CREATE INDEX ix_notes_category_id ON notes (category_id)""",
    """CREATE INDEX ix_notes_document_type ON notes (document_type)""",
    """CREATE INDEX ix_notes_order ON notes ("order")""",
    """CREATE INDEX ix_notes_project_id ON notes (project_id)""",
    """CREATE INDEX ix_pending_project_changes_model_id ON pending_project_changes (model_id)""",
    """CREATE INDEX ix_pending_project_changes_project_id ON pending_project_changes (project_id)""",
    """CREATE INDEX ix_pending_project_changes_project_status_created_at ON pending_project_changes (project_id, status, created_at)""",
    """CREATE INDEX ix_pending_project_changes_project_target ON pending_project_changes (project_id, target_type, target_id)""",
    """CREATE INDEX ix_pending_project_changes_source_message_id ON pending_project_changes (source_message_id)""",
    """CREATE INDEX ix_pending_project_changes_source_task_id ON pending_project_changes (source_task_id)""",
    """CREATE INDEX ix_plan_todos_created_at ON plan_todos (created_at)""",
    """CREATE INDEX ix_plan_todos_plan_id ON plan_todos (plan_id)""",
    """CREATE INDEX ix_plan_todos_sort_index ON plan_todos (sort_index)""",
    """CREATE INDEX ix_plan_todos_status ON plan_todos (status)""",
    """CREATE INDEX ix_plans_created_at ON plans (created_at)""",
    """CREATE INDEX ix_project_folders_order ON project_folders ("order")""",
    """CREATE INDEX ix_project_folders_project_id ON project_folders (project_id)""",
    """CREATE INDEX ix_project_folders_scope ON project_folders (scope)""",
    """CREATE INDEX ix_project_import_bindings_project_id ON project_import_bindings (project_id)""",
    """CREATE INDEX ix_project_import_bindings_project_source ON project_import_bindings (project_id, rule_id, source_path)""",
    """CREATE INDEX ix_prompt_chain_versions_prompt_id ON prompt_chain_versions (prompt_id)""",
    """CREATE INDEX ix_prompt_entries_uid ON prompt_entries (uid)""",
    """CREATE INDEX ix_retrieval_chapter_index_states_chapter_id ON retrieval_chapter_index_states (chapter_id)""",
    """CREATE INDEX ix_retrieval_chapter_index_states_embedding_model_ref_id ON retrieval_chapter_index_states (embedding_model_ref_id)""",
    """CREATE INDEX ix_retrieval_chapter_index_states_index_key ON retrieval_chapter_index_states (index_key)""",
    """CREATE INDEX ix_retrieval_chapter_index_states_indexed_at ON retrieval_chapter_index_states (indexed_at)""",
    """CREATE INDEX ix_retrieval_chapter_index_states_item_id ON retrieval_chapter_index_states (item_id)""",
    """CREATE INDEX ix_retrieval_chapter_index_states_job_id ON retrieval_chapter_index_states (job_id)""",
    """CREATE INDEX ix_retrieval_chapter_index_states_project_id ON retrieval_chapter_index_states (project_id)""",
    """CREATE INDEX ix_retrieval_chapter_index_states_status ON retrieval_chapter_index_states (status)""",
    """CREATE INDEX ix_retrieval_chapter_index_states_updated_at ON retrieval_chapter_index_states (updated_at)""",
    """CREATE INDEX ix_retrieval_indexes_embedding_model_ref_id ON retrieval_indexes (embedding_model_ref_id)""",
    """CREATE UNIQUE INDEX ix_retrieval_indexes_index_key ON retrieval_indexes (index_key)""",
    """CREATE INDEX ix_retrieval_indexes_status ON retrieval_indexes (status)""",
    """CREATE INDEX ix_retrieval_indexes_table_name ON retrieval_indexes (table_name)""",
    """CREATE INDEX ix_revision_chapter_snapshots_chapter_id ON revision_chapter_snapshots (chapter_id)""",
    """CREATE INDEX ix_revision_chapter_snapshots_created_at ON revision_chapter_snapshots (created_at)""",
    """CREATE INDEX ix_revision_chapter_snapshots_project_id ON revision_chapter_snapshots (project_id)""",
    """CREATE INDEX ix_revision_chapter_snapshots_revision_id ON revision_chapter_snapshots (revision_id)""",
    """CREATE INDEX ix_revision_chapter_snapshots_volume_id ON revision_chapter_snapshots (volume_id)""",
    """CREATE INDEX ix_revision_character_snapshots_character_id ON revision_character_snapshots (character_id)""",
    """CREATE INDEX ix_revision_character_snapshots_created_at ON revision_character_snapshots (created_at)""",
    """CREATE INDEX ix_revision_character_snapshots_project_id ON revision_character_snapshots (project_id)""",
    """CREATE INDEX ix_revision_character_snapshots_revision_id ON revision_character_snapshots (revision_id)""",
    """CREATE INDEX ix_revision_note_category_snapshots_category_id ON revision_note_category_snapshots (category_id)""",
    """CREATE INDEX ix_revision_note_category_snapshots_created_at ON revision_note_category_snapshots (created_at)""",
    """CREATE INDEX ix_revision_note_category_snapshots_parent_id ON revision_note_category_snapshots (parent_id)""",
    """CREATE INDEX ix_revision_note_category_snapshots_project_id ON revision_note_category_snapshots (project_id)""",
    """CREATE INDEX ix_revision_note_category_snapshots_revision_id ON revision_note_category_snapshots (revision_id)""",
    """CREATE INDEX ix_revision_note_snapshots_category_id ON revision_note_snapshots (category_id)""",
    """CREATE INDEX ix_revision_note_snapshots_created_at ON revision_note_snapshots (created_at)""",
    """CREATE INDEX ix_revision_note_snapshots_note_id ON revision_note_snapshots (note_id)""",
    """CREATE INDEX ix_revision_note_snapshots_project_id ON revision_note_snapshots (project_id)""",
    """CREATE INDEX ix_revision_note_snapshots_revision_id ON revision_note_snapshots (revision_id)""",
    """CREATE INDEX ix_revision_world_entry_snapshots_created_at ON revision_world_entry_snapshots (created_at)""",
    """CREATE INDEX ix_revision_world_entry_snapshots_entry_id ON revision_world_entry_snapshots (entry_id)""",
    """CREATE INDEX ix_revision_world_entry_snapshots_entry_order ON revision_world_entry_snapshots (entry_order)""",
    """CREATE INDEX ix_revision_world_entry_snapshots_project_id ON revision_world_entry_snapshots (project_id)""",
    """CREATE INDEX ix_revision_world_entry_snapshots_revision_id ON revision_world_entry_snapshots (revision_id)""",
    """CREATE INDEX ix_revision_world_entry_snapshots_uid ON revision_world_entry_snapshots (uid)""",
    """CREATE INDEX ix_revision_world_entry_snapshots_world_info_id ON revision_world_entry_snapshots (world_info_id)""",
    """CREATE INDEX ix_revisions_created_at ON revisions (created_at)""",
    """CREATE INDEX ix_revisions_finished_at ON revisions (finished_at)""",
    """CREATE INDEX ix_revisions_graph_thread_id ON revisions (graph_thread_id)""",
    """CREATE INDEX ix_revisions_is_checkpoint ON revisions (is_checkpoint)""",
    """CREATE INDEX ix_revisions_parent_revision_id ON revisions (parent_revision_id)""",
    """CREATE INDEX ix_revisions_pre_run_checkpoint_id ON revisions (pre_run_checkpoint_id)""",
    """CREATE INDEX ix_revisions_project_id ON revisions (project_id)""",
    """CREATE INDEX ix_revisions_revision_type ON revisions (revision_type)""",
    """CREATE INDEX ix_revisions_started_at ON revisions (started_at)""",
    """CREATE INDEX ix_revisions_status ON revisions (status)""",
    """CREATE INDEX ix_revisions_task_id ON revisions (task_id)""",
    """CREATE INDEX ix_revisions_user_message_id ON revisions (user_message_id)""",
    """CREATE INDEX ix_revisions_user_message_seq ON revisions (user_message_seq)""",
    """CREATE UNIQUE INDEX ix_settings_key ON settings ("key")""",
    """CREATE INDEX ix_skill_reference_docs_skill_db_id ON skill_reference_docs (skill_db_id)""",
    """CREATE INDEX ix_skills_is_enabled ON skills (is_enabled)""",
    """CREATE INDEX ix_task_messages_agent_id ON task_messages (agent_id)""",
    """CREATE INDEX ix_task_messages_correlation_id ON task_messages (correlation_id)""",
    """CREATE INDEX ix_task_messages_created_at ON task_messages (created_at)""",
    """CREATE INDEX ix_task_messages_display_channel ON task_messages (display_channel)""",
    """CREATE INDEX ix_task_messages_message_status ON task_messages (message_status)""",
    """CREATE INDEX ix_task_messages_message_type ON task_messages (message_type)""",
    """CREATE INDEX ix_task_messages_role ON task_messages (role)""",
    """CREATE INDEX ix_task_messages_task_id ON task_messages (task_id)""",
    """CREATE INDEX ix_task_messages_tool_call_id ON task_messages (tool_call_id)""",
    """CREATE INDEX ix_tasks_agent_session_id ON tasks (agent_session_id)""",
    """CREATE INDEX ix_tasks_current_message_id ON tasks (current_message_id)""",
    """CREATE INDEX ix_tasks_current_revision_id ON tasks (current_revision_id)""",
    """CREATE INDEX ix_tasks_folder_id ON tasks (folder_id)""",
    """CREATE INDEX ix_tasks_is_favorited ON tasks (is_favorited)""",
    """CREATE INDEX ix_tasks_mode ON tasks (mode)""",
    """CREATE INDEX ix_tasks_project_id ON tasks (project_id)""",
    """CREATE INDEX ix_world_info_entries_agent_visibility ON world_info_entries (agent_visibility)""",
    """CREATE INDEX ix_world_info_entries_folder_id ON world_info_entries (folder_id)""",
    """CREATE INDEX ix_world_info_entries_order ON world_info_entries ("order")""",
    """CREATE INDEX ix_world_info_entries_uid ON world_info_entries (uid)""",
    """CREATE INDEX ix_world_info_entries_world_info_id ON world_info_entries (world_info_id)""",
    """CREATE UNIQUE INDEX ix_world_info_project_id ON world_info (project_id)""",
    """CREATE INDEX ix_writing_activity_events_agent_session_id ON writing_activity_events (agent_session_id)""",
    """CREATE INDEX ix_writing_activity_events_chapter_id ON writing_activity_events (chapter_id)""",
    """CREATE INDEX ix_writing_activity_events_created_at ON writing_activity_events (created_at)""",
    """CREATE INDEX ix_writing_activity_events_operation ON writing_activity_events (operation)""",
    """CREATE INDEX ix_writing_activity_events_project_id ON writing_activity_events (project_id)""",
    """CREATE INDEX ix_writing_activity_events_revision_id ON writing_activity_events (revision_id)""",
    """CREATE INDEX ix_writing_activity_events_source ON writing_activity_events (source)""",
    """CREATE INDEX ix_writing_activity_events_task_id ON writing_activity_events (task_id)""",
    """CREATE UNIQUE INDEX uq_plans_session_id ON plans (session_id)""",
)


def upgrade() -> None:
    for statement in BASELINE_DDL:
        op.execute(sa.text(statement))


def downgrade() -> None:
    raise RuntimeError("The 20260908 baseline has no downgrade; restore a backup instead.")
